<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Dashboard_oxd-icon bi-caret-down-fill oxd_d2fd49</name>
   <tag></tag>
   <elementGuidId>17ca3c00-5131-43f4-8f35-ff34dff991d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/header/div/div[2]/ul/li/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.oxd-icon.bi-caret-down-fill.oxd-userdropdown-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>572c78a6-2f7b-4548-afd5-1eac38533bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-icon bi-caret-down-fill oxd-userdropdown-icon</value>
      <webElementGuid>ce1e4616-48f1-44b5-8916-0dbb350f04a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-navigation&quot;]/header[@class=&quot;oxd-topbar&quot;]/div[@class=&quot;oxd-topbar-header&quot;]/div[@class=&quot;oxd-topbar-header-userarea&quot;]/ul[1]/li[@class=&quot;oxd-userdropdown&quot;]/span[@class=&quot;oxd-userdropdown-tab&quot;]/i[@class=&quot;oxd-icon bi-caret-down-fill oxd-userdropdown-icon&quot;]</value>
      <webElementGuid>a3fd85df-1f50-421f-ac3b-fea34ec00a03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/header/div/div[2]/ul/li/span/i</value>
      <webElementGuid>e7cf8f7c-8c9d-446e-b588-de90867b7cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>9aa7518f-4f40-4f5e-8fa3-b60cc5f3411f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
