<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Elemental Selenium</name>
   <tag></tag>
   <elementGuidId>7258f35d-d9e9-4157-8f9a-3686d7701cd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.large-4.large-centered.columns > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-footer']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4524ded7-a487-44b2-b805-769fd09ec015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0a983949-99af-44d9-bfc8-12c17f2b53bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://elementalselenium.com/</value>
      <webElementGuid>ffc27ddd-7f4b-43f2-875b-1711ebe20377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Elemental Selenium</value>
      <webElementGuid>7d0171e7-45ae-4990-bc30-c702038dce27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-footer&quot;)/div[@class=&quot;large-4 large-centered columns&quot;]/div[1]/a[1]</value>
      <webElementGuid>9f9e4fef-8f38-405b-a73a-3ea519ec9d5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-footer']/div/div/a</value>
      <webElementGuid>dad461e9-890f-49b1-8f44-2de68e18922d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Elemental Selenium')]</value>
      <webElementGuid>f9577f9b-f5b1-4e8b-936d-57054910fb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A/B Test Variation 1'])[1]/following::a[1]</value>
      <webElementGuid>d01038fa-ef14-4820-97bc-58f82b2b80fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Elemental Selenium']/parent::*</value>
      <webElementGuid>20ccf589-8a53-48ff-a63b-df73c0be7200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://elementalselenium.com/']</value>
      <webElementGuid>9436c065-c9ef-43e4-be39-9f746aecbf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>8e8985da-fae2-458c-b034-be3de2fd6789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://elementalselenium.com/' and (text() = 'Elemental Selenium' or . = 'Elemental Selenium')]</value>
      <webElementGuid>afddf1fd-a28e-4269-96b8-e906420bb93e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
